{% set version = "2.8.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-readmzxmldata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/readMzXmlData_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/readMzXmlData/readMzXmlData_{{ version }}.tar.gz
  sha256: 131936e52a8437f3d9667772d3c2e16518ccecb6bdf3365814c18e007cda01cf

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-xml
    - r-base64enc
    - r-digest
  run:
    - r-base
    - r-xml
    - r-base64enc
    - r-digest

test:
  commands:
    - $R -e "library('readMzXmlData')"           # [not win]
    - "\"%R%\" -e \"library('readMzXmlData')\""  # [win]

about:
  home: http://strimmerlab.org/software/maldiquant/ https://github.com/sgibb/readMzXmlData/
  license: GPL-3.0-or-later
  summary: Functions for reading mass spectrometry data in mzXML format.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ArneKr
    - FrodePedersen
    - MathiasHaudgaard

# Package: readMzXmlData
# Version: 2.8.1
# Date: 2015-09-16
# Title: Reads Mass Spectrometry Data in mzXML Format
# Authors@R: person("Sebastian", "Gibb", role=c("aut", "cre"), email="mail@sebastiangibb.de")
# Depends: R (>= 2.15.0)
# Imports: base64enc, digest, XML
# Description: Functions for reading mass spectrometry data in mzXML format.
# License: GPL (>= 3)
# URL: http://strimmerlab.org/software/maldiquant/ https://github.com/sgibb/readMzXmlData/
# BugReports: https://github.com/sgibb/readMzXmlData/issues/
# LazyLoad: yes
# NeedsCompilation: no
# Packaged: 2015-09-16 08:08:30 UTC; sebastian
# Author: Sebastian Gibb [aut, cre]
# Maintainer: Sebastian Gibb <mail@sebastiangibb.de>
# Repository: CRAN
# Date/Publication: 2015-09-16 12:54:49
