appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 27Ux7tHscP0py+ybHU+3NEPGAJOW1cKxy5CMN4NfF0SV/inpXw5FibltcqwM6aZ55SbrpRfwikH5Lsi63kBV0YORbditsIslsCknGDJ7prl8oPTIIFTurQp98bh8O61rRHWnVD5pKkZ7xu9rdoOAm1hBwQPsn//4NXJjNGqvOnTboD7QBp0SeLJyb3FUoEO1gK4J+ke0Srl7R/2Us9KR92dD4BR/qcm4FKmelHMQL15Xh2eFpDjXln6CI4EJj6Av+pHUy50JJWYf8WneAokXvi7K0gT49f85iAyhXa3O9i14bTVN7gz8pZV5Gu74dg6IkMiYzCbA0EVOOLC+1SJPwGaRKjlvXwBVC8ow+UwPbPIPmod5qcjuuGwWiYsAbkBhaeYF65NRKN5cjD7HtSkIaD9vbDpDb7RZtpCaMjAkvgiyXho9Dkt5eF4cFd65502ZBNabEsHm1ZP3jS6JoouM6vQ+TiKpkxqVO5Mj/H1JGmEkopb9k4PO/HBFZ4ywdD6kBOLlId44OJonHSN/ckcnj8ZfHIDGn8hkzRiDOIC8QIhmGLeOt0Ea6ORnHRgHAPDi6iVTg9YvUgagU8KgXM+aq9F4P3I6xXLlgZZbToSvTGOAyEWL9GkBLSLaSjz2nxkPvgdhIuerucGLOujv369uTFl5yOYJwbrdij/hekvywFc=
conda_forge_output_validation: false
